// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bug': string;
  'dragon': string;
  'electric': string;
  'fairy': string;
  'fighting': string;
  'fire': string;
  'ghost': string;
  'gosth': string;
  'grass': string;
  'ground': string;
  'ice': string;
  'infoWrap': string;
  'label': string;
  'labelWrap': string;
  'normal': string;
  'pictureWrap': string;
  'poison': string;
  'psyich': string;
  'root': string;
  'statItem': string;
  'statValue': string;
  'statWrap': string;
  'titleName': string;
  'water': string;
}
export const cssExports: CssExports;
export default cssExports;
