// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'heading': string;
  'sizeL': string;
  'sizeM': string;
  'sizeXL': string;
}
export const cssExports: CssExports;
export default cssExports;
