// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  footer: string;
  footerright: string;
}
export const cssExports: CssExports;
export default cssExports;
